# Generated by Django 5.1 on 2024-08-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genre_ids',
        ),
    ]
