# Generated by Django 5.1 on 2024-08-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_genre_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(),
        ),
    ]
