# Generated by Django 5.1 on 2024-08-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre_ids',
        ),
    ]
