# Generated by Django 5.1 on 2024-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_film_genre_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre_ids',
            field=models.ManyToManyField(null=True, to='films.filmgenre'),
        ),
    ]
